// IPP - Default Clinical Question Set for Chilean Women's-Health Intake
// (Gynecology & Pelvic-Floor). Source: clinical research deliverable v1.
// 4 tabs (Datos personales, Antecedentes generales, Ginecología, Piso
// pélvico). Validated instruments (ICIQ-UI SF Chilean, AUDIT-C Chilean,
// Wexner/CCIS) embedded; long instruments (PFDI-20, PISQ-12) linked.

import type { FormSchema, Question } from "./types.ts";

const TABS: FormSchema["tabs"] = [
  { id: "datosPersonales",       label: "Datos",        icon: "person.text.rectangle", order: 1 },
  { id: "antecedentesGenerales", label: "Antecedentes", icon: "list.clipboard",        order: 2 },
  { id: "ginecologia",           label: "Ginecología",  icon: "heart.text.square",     order: 3 },
  { id: "pisoPelvico",           label: "Piso pélvico", icon: "figure.stand",          order: 4 },
];

// Helper so we can express order per tab inline.
function q(
  tab: string,
  order: number,
  body: Omit<Question, "tab" | "order">
): Question {
  return { ...body, tab, order };
}

const DATOS: Question[] = [
  q("datosPersonales", 1, { id: "nombres", label: "Nombres", labelEn: "First names", type: "text", tier: "essential",
    rationale: "Identificación básica del paciente en la ficha clínica (Ley 20.584).",
    source: "Ley 20.584 / Decreto 41 sobre Fichas Clínicas" }),
  q("datosPersonales", 2, { id: "apellidoPaterno", label: "Apellido paterno", labelEn: "Paternal surname", type: "text", tier: "essential",
    rationale: "Convención chilena de doble apellido.", source: "Registro Civil" }),
  q("datosPersonales", 3, { id: "apellidoMaterno", label: "Apellido materno", labelEn: "Maternal surname", type: "text", tier: "essential",
    rationale: "Convención chilena de doble apellido.", source: "Registro Civil" }),
  q("datosPersonales", 4, { id: "rut", label: "RUT", labelEn: "RUT (national ID)", type: "text", tier: "essential",
    rationale: "Identificador único nacional; validar dígito verificador con módulo 11 (resultado 10 = K, 11 = 0).",
    source: "Servicio de Impuestos Internos / Registro Civil - algoritmo módulo 11" }),
  q("datosPersonales", 5, { id: "fechaNacimiento", label: "Fecha de nacimiento", labelEn: "Date of birth", type: "date", tier: "essential",
    rationale: "La edad determina elegibilidad de tamizajes GES (PAP 25–64; mamografía 50–59).",
    source: "Guía GES CaCu MINSAL 2015; Decreto GES N°72/2022" }),
  q("datosPersonales", 6, { id: "sexoRegistral", label: "Sexo registral", labelEn: "Registered sex", type: "picker",
    options: ["Femenino","Masculino","Otro"], tier: "commonly", hidden: true,
    rationale: "Población objetivo femenina; campo opcional para identidad de género.",
    source: "Ley 21.120 (identidad de género)" }),
  q("datosPersonales", 7, { id: "telefono", label: "Teléfono de contacto", labelEn: "Contact phone", type: "text", tier: "essential",
    rationale: "Contacto y entrega de resultados.", source: "Ley 20.584" }),
  q("datosPersonales", 8, { id: "email", label: "Correo electrónico", labelEn: "Email", type: "text", tier: "commonly",
    rationale: "Entrega del código de acceso web del paciente." }),
  q("datosPersonales", 9, { id: "region", label: "Región", labelEn: "Region", type: "picker", tier: "commonly",
    options: ["Metropolitana de Santiago","Valparaíso","Biobío","Maule","La Araucanía","Libertador Gral. Bernardo O'Higgins","Los Lagos","Coquimbo","Antofagasta","Ñuble","Los Ríos","Tarapacá","Atacama","Arica y Parinacota","Magallanes y de la Antártica Chilena","Aysén del Gral. Carlos Ibáñez del Campo"],
    rationale: "Subdivisión administrativa chilena; ordenada por población.",
    source: "División político-administrativa de Chile (SUBDERE)" }),
  q("datosPersonales", 10, { id: "comuna", label: "Comuna", labelEn: "Comuna (municipality)", type: "text", tier: "commonly",
    placeholder: "Comuna de residencia",
    rationale: "Comuna dependiente de la región seleccionada (poblar dinámicamente).",
    source: "SUBDERE" }),
  q("datosPersonales", 11, { id: "direccion", label: "Dirección", labelEn: "Address", type: "address", tier: "commonly",
    rationale: "Domicilio para contacto y referencia territorial.",
    source: "Ley 20.584" }),
  q("datosPersonales", 12, { id: "prevision", label: "Previsión / sistema de salud", labelEn: "Health insurance system", type: "picker",
    options: ["FONASA","Isapre","Particular","Otra (FF.AA. / Dipreca / Capredena)"], tier: "essential",
    rationale: "Determina cobertura GES y modalidad de atención (MAI/MLE).",
    source: "FONASA / Superintendencia de Salud" }),
  q("datosPersonales", 13, { id: "tramoFonasa", label: "Tramo FONASA", labelEn: "FONASA bracket", type: "picker",
    options: ["A","B","C","D"], dependsOn: "prevision", dependsOnValue: "FONASA", tier: "commonly",
    rationale: "Tramos A–D según ingreso (2026: B ≤ $539.000; C $539.001–$786.940; D > $786.940); relevante para copago en MLE.",
    source: "FONASA" }),
  q("datosPersonales", 14, { id: "nombreIsapre", label: "Nombre Isapre", labelEn: "Isapre name", type: "text",
    dependsOn: "prevision", dependsOnValue: "Isapre", tier: "commonly", hidden: true,
    rationale: "Identifica la aseguradora privada.", source: "Superintendencia de Salud" }),
  q("datosPersonales", 15, { id: "nivelEducacional", label: "Nivel educacional", labelEn: "Education level", type: "picker",
    options: ["Ninguna","Básica","Media","Técnica","Universitaria","Postgrado"], tier: "optional", hidden: true,
    rationale: "Determinante social de salud; opcional/follow-up.",
    source: "Manual Obstetricia y Ginecología UC 2023" }),
  q("datosPersonales", 16, { id: "ocupacion", label: "Ocupación", labelEn: "Occupation", type: "text", tier: "optional", hidden: true,
    rationale: "Trabajo con esfuerzo físico es factor de riesgo de disfunción del piso pélvico.",
    source: "Manual UC 2023" }),
  q("datosPersonales", 17, { id: "puebloOriginario", label: "Pertenencia a pueblo originario", labelEn: "Indigenous group", type: "picker",
    options: ["No","Mapuche","Aymara","Diaguita","Quechua","Rapa Nui","Colla","Otro"], tier: "optional", hidden: true,
    rationale: "Modelo de salud intercultural (Ley 20.584).",
    source: "Ley 20.584" }),
  q("datosPersonales", 18, { id: "consentimientoDatos",
    label: "Autorizo el registro de mis datos de salud en mi ficha clínica, los que serán tratados de forma confidencial conforme a la Ley 20.584 y la Ley 19.628.",
    labelEn: "I authorize the recording of my health data in my clinical record, to be processed confidentially under Law 20.584 and Law 19.628.",
    type: "boolean", tier: "essential",
    rationale: "LEGAL: consentimiento para tratamiento de datos sensibles; texto literal requerido.",
    source: "Ley 20.584; Ley 19.628" }),
];

const ANTECEDENTES: Question[] = [
  q("antecedentesGenerales", 1, { id: "peso", label: "Peso (kg)", labelEn: "Weight (kg)", type: "number", tier: "essential",
    rationale: "Componente del IMC; obesidad es factor de riesgo de IU y prolapso.",
    source: "MINSAL - EMP" }),
  q("antecedentesGenerales", 2, { id: "talla", label: "Talla (cm)", labelEn: "Height (cm)", type: "number", tier: "essential",
    rationale: "Componente del IMC.", source: "MINSAL EMP" }),
  q("antecedentesGenerales", 3, { id: "imc", label: "IMC (calculado)", labelEn: "BMI (calculated)", type: "number", tier: "commonly",
    rationale: "Calculado automáticamente de peso/talla.", source: "OMS" }),
  q("antecedentesGenerales", 4, { id: "enfermedadesCronicas", label: "Enfermedades crónicas", labelEn: "Chronic conditions", type: "multiselect",
    options: ["Ninguna","Hipertensión arterial (HTA)","Diabetes mellitus 2","Hipotiroidismo","Dislipidemia","Asma/EPOC","Depresión/ansiedad","Enfermedad renal crónica"],
    allowCustom: true, tier: "essential",
    rationale: "HTA/DM2/hipotiroidismo son prevalentes y modifican el manejo.",
    source: "MINSAL - Guías GES de enfermedades crónicas" }),
  q("antecedentesGenerales", 5, { id: "cirugiasPrevias", label: "Cirugías previas", labelEn: "Previous surgeries", type: "multiselect",
    options: ["Ninguna","Cesárea","Histerectomía","Colecistectomía","Apendicectomía","Cirugía de incontinencia/prolapso","Esterilización quirúrgica"],
    allowCustom: true, tier: "essential",
    rationale: "La cirugía pélvica previa altera anatomía y función del piso pélvico.",
    source: "Manual UC 2023" }),
  q("antecedentesGenerales", 6, { id: "medicamentos", label: "Fármacos en uso", labelEn: "Current medications", type: "multiselect",
    options: [], allowCustom: true, tier: "essential",
    rationale: "Polifarmacia; diuréticos y anticolinérgicos modifican síntomas urinarios.",
    source: "MINSAL" }),
  q("antecedentesGenerales", 7, { id: "alergias", label: "Alergias", labelEn: "Allergies", type: "multiselect",
    options: ["Ninguna conocida","Penicilina","AINEs","Yodo/medio de contraste","Látex","Sulfas"],
    allowCustom: true, tier: "essential",
    rationale: "Seguridad clínica.", source: "Anamnesis (Manual UC 2023)" }),
  q("antecedentesGenerales", 8, { id: "fuma", label: "¿Fuma actualmente?", labelEn: "Do you currently smoke?", type: "boolean", tier: "essential",
    rationale: "Tabaquismo: riesgo cardiovascular y tos crónica (asociada a IU de esfuerzo).",
    source: "MINSAL; Fagerström FTND" }),
  q("antecedentesGenerales", 9, { id: "cigarrillosDia", label: "Cigarrillos por día", labelEn: "Cigarettes per day", type: "number",
    dependsOn: "fuma", dependsOnValue: true, tier: "commonly",
    rationale: "Ítem Fagerström abreviado.", source: "Fagerström FTND (versión española)" }),
  q("antecedentesGenerales", 10, { id: "fagerstromPrimerCig",
    label: "¿Cuánto tiempo pasa desde que despierta hasta su primer cigarrillo?",
    labelEn: "How soon after waking do you smoke your first cigarette?", type: "picker",
    options: ["Más de 60 min","31–60 min","6–30 min","Menos de 5 min"],
    dependsOn: "fuma", dependsOnValue: true, tier: "optional", hidden: true,
    rationale: "Ítem de mayor peso del Fagerström.", source: "Fagerström FTND (Heatherton 1991)" }),
  q("antecedentesGenerales", 11, { id: "alcoholFrecuencia",
    label: "¿Con qué frecuencia consume bebidas alcohólicas?",
    labelEn: "How often do you have a drink containing alcohol?", type: "picker",
    options: ["Nunca","1 vez al mes o menos","2–4 veces al mes","2–3 veces por semana","4 o más veces por semana"],
    tier: "commonly",
    rationale: "AUDIT-C ítem 1.", source: "AUDIT validado en Chile (Alvarado et al., Rev Med Chile 2009)" }),
  q("antecedentesGenerales", 12, { id: "alcoholCantidad",
    label: "En un día de consumo, ¿cuántos tragos toma habitualmente?",
    labelEn: "How many drinks on a typical drinking day?", type: "picker",
    options: ["1–2","3–4","5–6","7–9","10 o más"],
    dependsOn: "alcoholFrecuencia", tier: "commonly",
    rationale: "AUDIT-C ítem 2.", source: "AUDIT-C (Alvarado 2009)" }),
  q("antecedentesGenerales", 13, { id: "alcoholBinge",
    label: "¿Con qué frecuencia toma 6 o más tragos en una sola ocasión?",
    labelEn: "How often do you have 6 or more drinks on one occasion?", type: "picker",
    options: ["Nunca","Menos de 1 vez al mes","Mensualmente","Semanalmente","A diario o casi a diario"],
    dependsOn: "alcoholFrecuencia", tier: "commonly",
    rationale: "AUDIT-C ítem 3. AUDIT total ≥6 = consumo de riesgo en Chile (sens 83%, espec 88%).",
    source: "AUDIT-C; Alvarado 2009" }),
  q("antecedentesGenerales", 14, { id: "actividadFisica",
    label: "¿Realiza actividad física regular?", labelEn: "Regular physical activity?", type: "picker",
    options: ["Sedentaria","1–2 veces/semana","3 o más veces/semana"], tier: "commonly",
    rationale: "Estilo de vida; relevante para salud del piso pélvico.", source: "MINSAL EMP" }),
  q("antecedentesGenerales", 15, { id: "screeningVIF",
    label: "¿Se siente segura en su hogar y en sus relaciones? ¿Ha sufrido maltrato físico, psicológico o sexual?",
    labelEn: "Do you feel safe at home and in your relationships? Have you experienced physical, psychological or sexual abuse?",
    type: "boolean", tier: "commonly", hidden: true,
    rationale: "LEGAL: tamizaje VIF. Respuesta positiva con señales de delito activa deber de denuncia (CPP Art. 175 letra d; Ley 19.968 Art. 84). Preguntar en privado.",
    source: "Ley 20.066; CPP Art. 175 letra d; Ley 19.968 Art. 84" }),
];

const GINECOLOGIA: Question[] = [
  q("ginecologia", 1, { id: "menarquia", label: "Edad de menarquia", labelEn: "Age at menarche", type: "number", tier: "commonly",
    rationale: "Antecedente ginecológico estándar.", source: "Manual UC 2023" }),
  q("ginecologia", 2, { id: "fur", label: "Fecha de última regla (FUR)", labelEn: "Date of last menstrual period", type: "date", tier: "essential",
    rationale: "Orienta estado hormonal y descarta embarazo.", source: "Manual UC 2023" }),
  q("ginecologia", 3, { id: "cicloMenstrual", label: "Ciclo menstrual (días de sangrado / días de ciclo)",
    labelEn: "Menstrual cycle (bleeding days / cycle length)", type: "text", tier: "commonly",
    placeholder: "4/28",
    rationale: "Notación chilena tipo menstrual (TM), p.ej. 4/28.", source: "Manual UC 2023" }),
  q("ginecologia", 4, { id: "estadoMenopausico", label: "Estado menopáusico", labelEn: "Menopausal status", type: "picker",
    options: ["Premenopausia","Perimenopausia","Postmenopausia"], tier: "commonly",
    rationale: "El climaterio es relevante para síntomas urogenitales y de piso pélvico.",
    source: "MINSAL - orientaciones climaterio" }),
  q("ginecologia", 5, { id: "gestas", label: "Gestas (G)", labelEn: "Gravidity (G)", type: "number", tier: "essential",
    rationale: "Componente de la fórmula obstétrica chilena (GPA).", source: "Manual UC 2023" }),
  q("ginecologia", 6, { id: "partosVaginales", label: "Partos vaginales", labelEn: "Vaginal deliveries", type: "number", tier: "essential",
    rationale: "Los partos vaginales son el principal factor de riesgo de prolapso e IU.",
    source: "Rev Med Clín Las Condes - prolapso genital femenino" }),
  q("ginecologia", 7, { id: "cesareas", label: "Cesáreas", labelEn: "Cesarean deliveries", type: "number", tier: "essential",
    rationale: "Componente de la fórmula obstétrica.", source: "Manual UC 2023" }),
  q("ginecologia", 8, { id: "abortos", label: "Abortos", labelEn: "Abortions/miscarriages", type: "number", tier: "essential",
    rationale: "Componente GPA.", source: "Manual UC 2023" }),
  q("ginecologia", 9, { id: "ectopicos", label: "Embarazos ectópicos", labelEn: "Ectopic pregnancies", type: "number",
    tier: "optional", hidden: true,
    rationale: "Se consignan en diagnósticos; opcional en la fórmula.", source: "Manual UC 2023" }),
  q("ginecologia", 10, { id: "pesoRnMayor", label: "Peso del recién nacido más grande (g)", labelEn: "Largest newborn birth weight (g)",
    type: "number", tier: "optional", hidden: true,
    rationale: "La macrosomía es factor de riesgo de lesión del piso pélvico.",
    source: "Literatura uroginecológica (ICS/IUGA)" }),
  q("ginecologia", 11, { id: "episiotomiaDesgarro", label: "Antecedente de episiotomía o desgarro perineal",
    labelEn: "History of episiotomy or perineal tear", type: "picker",
    options: ["No","Episiotomía","Desgarro grado I–II","Desgarro grado III–IV","No sabe"],
    tier: "commonly", hidden: true,
    rationale: "Desgarros III–IV se asocian a incontinencia anal y disfunción.",
    source: "Wexner/CCIS; literatura de piso pélvico" }),
  q("ginecologia", 12, { id: "metodoAnticonceptivo", label: "Método anticonceptivo (MAC) actual",
    labelEn: "Current contraceptive method", type: "multiselect",
    options: ["Ninguno","ACO combinado","Progestágeno solo (PPS)","DIU de cobre (T-Cu)","DIU/SIU hormonal (T-LNG)","Implante subdérmico","Inyectable","Preservativo","Esterilización quirúrgica","MELA/método natural"],
    allowCustom: true, tier: "essential",
    rationale: "Regulación de fertilidad; canasta del sistema público. Matronas/matrones pueden prescribir (Ley 20.533).",
    source: "MINSAL - Normas Nacionales sobre Regulación de la Fertilidad 2014/2018" }),
  q("ginecologia", 13, { id: "fechaPap", label: "Fecha del último PAP", labelEn: "Date of last Pap smear", type: "date", tier: "essential",
    rationale: "Tamizaje CaCu GES: PAP cada 3 años en mujeres de 25 a 64 años.",
    source: "Guía GES Cáncer Cervicouterino MINSAL 2015" }),
  q("ginecologia", 14, { id: "resultadoPap", label: "Resultado del último PAP", labelEn: "Last Pap result", type: "picker",
    options: ["Normal","ASCUS","Lesión de bajo grado (NIE I)","Lesión de alto grado (NIE II/III)","ASC-H / AGUS","No recuerda"],
    tier: "commonly",
    rationale: "Clasificación Bethesda; toda PAP positiva se deriva a colposcopía.",
    source: "Guía GES CaCu 2015" }),
  q("ginecologia", 15, { id: "fechaVph", label: "Fecha del último test VPH", labelEn: "Date of last HPV test", type: "date",
    tier: "optional", hidden: true,
    rationale: "Test VPH 30–64 años donde está disponible.", source: "Guía GES CaCu 2015" }),
  q("ginecologia", 16, { id: "fechaMamografia", label: "Fecha de la última mamografía", labelEn: "Date of last mammogram",
    type: "date", tier: "essential",
    rationale: "Decreto GES N°72/2022: mujer 50–59 años, mamografía gratuita cada 3 años. Ley 21.551 eximió la orden médica.",
    source: "Decreto GES N°72/2022; Guía GES Cáncer de Mama MINSAL 2021" }),
  q("ginecologia", 17, { id: "resultadoMamografia", label: "Resultado de la última mamografía (BI-RADS)",
    labelEn: "Last mammogram result (BI-RADS)", type: "picker",
    options: ["BI-RADS 0","BI-RADS 1","BI-RADS 2","BI-RADS 3","BI-RADS 4","BI-RADS 5","BI-RADS 6","No recuerda"],
    tier: "commonly",
    rationale: "4 y 5 se notifican para activar GES.", source: "Guía GES Cáncer de Mama 2015/2021" }),
  q("ginecologia", 18, { id: "itsPrevias", label: "Antecedente de ITS", labelEn: "History of STIs", type: "multiselect",
    options: ["Ninguna","VPH","Clamidia","Gonorrea","Sífilis","Herpes genital","VIH"],
    allowCustom: true, tier: "optional", hidden: true,
    rationale: "Antecedente sexual relevante; opcional/especialidad.", source: "MINSAL - manejo de ITS" }),
];

const PISO: Question[] = [
  q("pisoPelvico", 1, { id: "motivoConsultaPP", label: "Motivo de consulta de piso pélvico",
    labelEn: "Pelvic-floor chief complaint", type: "multiselect",
    options: ["Incontinencia de orina","Urgencia / vejiga hiperactiva","Sensación de bulto / prolapso","Incontinencia fecal o de gases","Estreñimiento","Dolor / dispareunia"],
    allowCustom: true, tier: "essential",
    rationale: "Orienta y prioriza el resto del tab.",
    source: "ICS/IUGA - terminología de disfunción del piso pélvico" }),
  q("pisoPelvico", 2, { id: "pierdeOrina", label: "¿Pierde orina de forma involuntaria?",
    labelEn: "Do you leak urine involuntarily?", type: "boolean", tier: "essential",
    rationale: "Pregunta gatillo del ICIQ-UI SF.",
    source: "ICIQ-UI SF, versión español-chilena (Busquets & Serra, Rev Med Chile 2012)" }),
  q("pisoPelvico", 3, { id: "iciqFrecuencia", label: "¿Con qué frecuencia pierde orina?",
    labelEn: "How often do you leak urine?", type: "picker",
    options: ["Nunca (0)","Una vez a la semana (1)","2–3 veces por semana (2)","Una vez al día (3)","Varias veces al día (4)","Continuamente (5)"],
    dependsOn: "pierdeOrina", dependsOnValue: true, tier: "essential",
    rationale: "ICIQ-UI SF ítem 3 (frecuencia, 0–5).",
    source: "ICIQ-UI SF Chile (Busquets & Serra 2012)" }),
  q("pisoPelvico", 4, { id: "iciqCantidad",
    label: "Indique la cantidad de orina que cree que se le escapa habitualmente (lleve o no protección).",
    labelEn: "How much urine do you think you usually leak?", type: "picker",
    options: ["No se me escapa nada (0)","Muy poca cantidad (2)","Una cantidad moderada (4)","Mucha cantidad (6)"],
    dependsOn: "pierdeOrina", dependsOnValue: true, tier: "essential",
    rationale: "ICIQ-UI SF ítem 4 (cantidad; valores 0/2/4/6).",
    source: "ICIQ-UI SF Chile (Busquets & Serra 2012)" }),
  q("pisoPelvico", 5, { id: "iciqImpacto",
    label: "¿En qué medida estos escapes de orina han afectado su vida diaria? (0 = nada, 10 = mucho)",
    labelEn: "How much do these urine leaks affect your daily life? (0–10)", type: "number",
    dependsOn: "pierdeOrina", dependsOnValue: true, tier: "essential",
    rationale: "ICIQ-UI SF ítem 5 (impacto, 0–10). Total = 3+4+5 (0–21); >0 = IU.",
    source: "ICIQ-UI SF Chile (Busquets & Serra 2012)" }),
  q("pisoPelvico", 6, { id: "iciqSituaciones",
    label: "¿En qué situaciones pierde orina? (marque todas las que correspondan)",
    labelEn: "In which situations do you leak urine? (mark all that apply)", type: "multiselect",
    options: ["Al toser o estornudar","Al realizar esfuerzos físicos o ejercicio","Antes de llegar al baño","Sin motivo evidente","Mientras duerme","Al terminar de orinar y ya vestida","De forma continua"],
    allowCustom: false, dependsOn: "pierdeOrina", dependsOnValue: true, tier: "essential",
    rationale: "ICIQ-UI SF ítem 6 (no puntuado): clasifica esfuerzo vs urgencia vs mixta.",
    source: "ICIQ-UI SF Chile (Busquets & Serra 2012)" }),
  q("pisoPelvico", 7, { id: "urgencia", label: "¿Siente urgencia repentina y difícil de aguantar para orinar?",
    labelEn: "Do you feel a sudden urge to urinate that is difficult to defer?", type: "boolean", tier: "essential",
    rationale: "Ítem clave de urgencia / vejiga hiperactiva (ICIQ-OAB).",
    source: "ICIQ-OAB (iciq.net/iciq-oab)" }),
  q("pisoPelvico", 8, { id: "frecuenciaMiccional", label: "¿Cuántas veces orina durante el día?",
    labelEn: "How many times do you urinate during the day?", type: "number", tier: "commonly",
    rationale: "ICIQ-OAB - frecuencia diurna.", source: "ICIQ-OAB" }),
  q("pisoPelvico", 9, { id: "nicturia", label: "¿Cuántas veces se levanta a orinar durante la noche?",
    labelEn: "How many times do you get up at night to urinate?", type: "number", tier: "commonly",
    rationale: "ICIQ-OAB - nicturia.", source: "ICIQ-OAB" }),
  q("pisoPelvico", 10, { id: "sensacionBulto", label: "¿Siente o ve un bulto que se asoma por la vagina?",
    labelEn: "Do you feel or see a bulge protruding from the vagina?", type: "boolean", tier: "essential",
    rationale: "Síntoma cardinal de prolapso de órganos pélvicos (POPDI del PFDI-20).",
    source: "PFDI-20 (validación española, Sánchez-Sánchez 2013)" }),
  q("pisoPelvico", 11, { id: "popqEstadio", label: "Estadio POP-Q (examen clínico)",
    labelEn: "POP-Q stage (clinical exam)", type: "picker",
    options: ["0","I","II","III","IV"], tier: "commonly", hidden: true,
    rationale: "Estadificación POP-Q administrada por el clínico (no autorreportada).",
    source: "ICS/IUGA POP-Q" }),
  q("pisoPelvico", 12, { id: "incontinenciaFecal", label: "¿Pierde involuntariamente deposiciones o gases?",
    labelEn: "Do you involuntarily leak stool or gas?", type: "boolean", tier: "essential",
    rationale: "Pregunta gatillo del Wexner/CCIS.",
    source: "Wexner / CCIS (Jorge & Wexner 1993; PMID 8416784)" }),
  q("pisoPelvico", 13, { id: "wexnerSolido", label: "Incontinencia a deposiciones sólidas",
    labelEn: "Incontinence to solid stool", type: "picker",
    options: ["Nunca (0)","Rara vez (1)","A veces (2)","Generalmente (3)","Siempre (4)"],
    dependsOn: "incontinenciaFecal", dependsOnValue: true, tier: "commonly",
    rationale: "Ítem Wexner/CCIS.", source: "Wexner/CCIS (Jorge & Wexner 1993)" }),
  q("pisoPelvico", 14, { id: "wexnerLiquido", label: "Incontinencia a deposiciones líquidas",
    labelEn: "Incontinence to liquid stool", type: "picker",
    options: ["Nunca (0)","Rara vez (1)","A veces (2)","Generalmente (3)","Siempre (4)"],
    dependsOn: "incontinenciaFecal", dependsOnValue: true, tier: "commonly",
    rationale: "Ítem Wexner/CCIS.", source: "Wexner/CCIS (Jorge & Wexner 1993)" }),
  q("pisoPelvico", 15, { id: "wexnerGases", label: "Incontinencia a gases", labelEn: "Incontinence to gas", type: "picker",
    options: ["Nunca (0)","Rara vez (1)","A veces (2)","Generalmente (3)","Siempre (4)"],
    dependsOn: "incontinenciaFecal", dependsOnValue: true, tier: "commonly",
    rationale: "Ítem Wexner/CCIS.", source: "Wexner/CCIS (Jorge & Wexner 1993)" }),
  q("pisoPelvico", 16, { id: "wexnerProteccion", label: "Uso de protección / pañal",
    labelEn: "Use of pad / protective device", type: "picker",
    options: ["Nunca (0)","Rara vez (1)","A veces (2)","Generalmente (3)","Siempre (4)"],
    dependsOn: "incontinenciaFecal", dependsOnValue: true, tier: "commonly",
    rationale: "Ítem Wexner/CCIS.", source: "Wexner/CCIS (Jorge & Wexner 1993)" }),
  q("pisoPelvico", 17, { id: "wexnerEstiloVida", label: "Alteración del estilo de vida por la incontinencia",
    labelEn: "Lifestyle alteration due to incontinence", type: "picker",
    options: ["Nunca (0)","Rara vez (1)","A veces (2)","Generalmente (3)","Siempre (4)"],
    dependsOn: "incontinenciaFecal", dependsOnValue: true, tier: "commonly",
    rationale: "Ítem Wexner/CCIS; total 0 (continencia perfecta) a 20 (incontinencia completa).",
    source: "Wexner/CCIS (Jorge & Wexner 1993; PMID 8416784)" }),
  q("pisoPelvico", 18, { id: "estrenimiento", label: "¿Tiene estreñimiento o dificultad para evacuar?",
    labelEn: "Do you have constipation or difficulty evacuating?", type: "boolean", tier: "commonly",
    rationale: "Se asocia a disfunción de piso pélvico; si positivo, aplicar Wexner Constipation Score.",
    source: "Wexner Constipation Score (Agachan et al. 1996; PMID 8646957)" }),
  q("pisoPelvico", 19, { id: "dispareunia", label: "¿Tiene dolor durante las relaciones sexuales?",
    labelEn: "Do you have pain during sexual intercourse?", type: "boolean", tier: "commonly",
    rationale: "Disfunción sexual; gatillo para PISQ-12.",
    source: "PISQ-12 (validación española, Espuña-Pons 2008)" }),
  q("pisoPelvico", 20, { id: "linkPisq12", label: "Aplicar PISQ-12 completo (enlace)",
    labelEn: "Apply full PISQ-12 (link)", type: "boolean",
    dependsOn: "dispareunia", dependsOnValue: true, tier: "optional", hidden: true,
    rationale: "Cuestionario largo enlazado, no embebido, para mantener el tab usable.",
    source: "PISQ-12 (Espuña-Pons 2008)" }),
  q("pisoPelvico", 21, { id: "linkPfdi20", label: "Aplicar PFDI-20 completo (enlace)",
    labelEn: "Apply full PFDI-20 (link)", type: "boolean",
    tier: "optional", hidden: true,
    rationale: "Cuestionario largo (~10 min) enlazado; ítems triage ya están embebidos arriba.",
    source: "PFDI-20 (Sánchez-Sánchez 2013)" }),
];

export const CLINICAL_SCHEMA: FormSchema = {
  version: 1, // overridden by PUT - endpoint bumps it
  tabs: TABS,
  questions: [...DATOS, ...ANTECEDENTES, ...GINECOLOGIA, ...PISO],
};
